spring:
    application:
        name: CONFIG-DEV
eureka:
    instance:
        prefer-ip-address:  true
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            defaultZone: http://localhost:8761/eureka

